=== Upgrade
==== Version >=4.0.0
- Requires Quarkus 4 and Java 21.
- Quarkus now provides a Jackson 3 `tools.jackson.databind.json.JsonMapper` bean instead of a Jackson 2 `ObjectMapper`. Inject `JsonMapper` if you used the Quarkus mapper in your job workers.
- The Camunda client still uses Jackson 2 (`com.fasterxml.jackson`). Quarkus no longer brings Jackson 2 modules like `jackson-datatype-jsr310` transitively: add them yourself or move custom `io.camunda.client.api.JsonMapper` implementations to Jackson 3.
- Quarkus OpenTelemetry now exports via `http/protobuf` on port `4318` by default and samples 10% of traces outside dev mode.

==== Version >=3.0.0
- Migrated to new Dev Services api provided by Quarkus
- Camunda 8.10 client support
- Minimum required quarkus version is >= 3.25

==== Version >=2.0.0
- Renamed the project from `quarkus zeebe` to `quarkus camunda` to reflect the migration to  the new camunda client.
- All properties starting with `quarkus.zeebe` are now under `quarkus.camunda`.
- `quarkus.camunda.broker.gateway-address` needs to be a valid URL now. The new default is `http://localhost:26500` instead of `localhost:26500`.
- Quarkus Camunda uses by default REST. If you want to change this you need to set `quarkus.camunda.broker.use-grpc` to `true`.
- `quarkus.camunda.broker.plaintext` was removed as it is not supported by the camunda client anymore.
- Fixed ports configuration for dev services were removed, since it is not recommended by testcontainers.
- Removed debug exporter and all config options for this feature.
- Devservices use the Camunda Orchestration image now with an integrated H2 database.
- Dev UI was removed because it relied on the removed zeebe debug exporter.


==== Version >=0.8.0
In version `>=0.8.0` we replaced `@ZeebeWorker` with `@JobWorker` annotation.

==== Version >=0.7.0
In version `>=0.7.0` we removed the hazelcast dependency and https://github.com/camunda-community-hub/zeebe-simple-monitor[zeebe-simple-monitor]
for test and dev services. Now we do use https://github.com/camunda-community-hub/zeebe-test-container[zeebe-test-container] with https://github.com/camunda-community-hub/zeebe-test-container#debug-exporter[debug exporter]
and https://github.com/lorislab/zeebe-dev-monitor[zeebe-dev-monitor]. In test module we remove our assert API and switch to Camunda https://github.com/camunda/zeebe-process-test/blob/main/assertions/src/main/java/io/camunda/zeebe/process/test/assertions/BpmnAssert.java[BpmnAssert]
from https://github.com/camunda/zeebe-process-test[zeebe-process-test]. Test api migration: `io.quarkiverse.zeebe.test.BpmnAssert` -> `io.camunda.zeebe.process.test.assertions.BpmnAssert`
